spring:
  profiles:
    active: run

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
    min-response-size: 1024

---
spring:
  profiles: run
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/api?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&tinyInt1isBit=false
    username: root
    password: 123321
    driverClassName: org.mariadb.jdbc.Driver
---
spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  datasource:
#    url: jdbc:h2:./data
    username: sa
    password:
    driverClassName: org.h2.Driver