spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://localhost:3306/api
    username: root
    password: 123321
    driverClassName: org.mariadb.jdbc.Driver
    sqlScriptEncoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
    min-response-size: 1024