package br.com.jaa.server.features.usuario.enums;

public enum UsuarioServiceMessageEnum {
    USUARIO_ERROR_EMAIL_INVALIDO,
    USUARIO_ERROR_EMAIL_JA_CADASTRADO,
    USUARIO_ERROR_PASSWORD_INVALIDO,
    USUARIO_ERROR_NAO_LOGADO,
    USUARIO_SUCESS_USUARIO_CADASTRADO,
    USUARIO_ID_NAO_VALIDO,
    USUARIO_NAO_ENCONTRADO,
    USUARIO_CADASTRADO,
    USUARIO_INFO_INVALIDA;

}
